// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SertaCup_site.Data;

#nullable disable

namespace SertaCup_site.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250624185409_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SertaCup_site.Models.Classificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("derrotas")
                        .HasColumnType("int");

                    b.Property<int?>("empate")
                        .HasColumnType("int");

                    b.Property<int>("equipa")
                        .HasColumnType("int");

                    b.Property<int?>("golos_marcados")
                        .HasColumnType("int");

                    b.Property<int?>("golos_sofridos")
                        .HasColumnType("int");

                    b.Property<int>("grupo")
                        .HasColumnType("int");

                    b.Property<int?>("jogos_feitos")
                        .HasColumnType("int");

                    b.Property<int?>("pontos")
                        .HasColumnType("int");

                    b.Property<int?>("vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("classificacoes");
                });

            modelBuilder.Entity("SertaCup_site.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("campo")
                        .HasColumnType("int");

                    b.Property<bool>("começado")
                        .HasColumnType("bit");

                    b.Property<int>("equipa1")
                        .HasColumnType("int");

                    b.Property<int>("equipa2")
                        .HasColumnType("int");

                    b.Property<byte>("golos_equipa1")
                        .HasColumnType("tinyint");

                    b.Property<byte>("golos_equipa2")
                        .HasColumnType("tinyint");

                    b.Property<int?>("grupo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("hora_inicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("hora_inicio_2parte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("hora_prevista")
                        .HasColumnType("datetime2");

                    b.Property<bool>("interrompido")
                        .HasColumnType("bit");

                    b.Property<bool>("primeira_parte_terminada")
                        .HasColumnType("bit");

                    b.Property<string>("situacao_precaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tempo_pausado_1")
                        .HasColumnType("int");

                    b.Property<int>("tempo_pausado_2")
                        .HasColumnType("int");

                    b.Property<bool>("terminado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("jogos");
                });

            modelBuilder.Entity("SertaCup_site.Models.Grupo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte>("equipa1")
                        .HasColumnType("tinyint");

                    b.Property<byte>("equipa2")
                        .HasColumnType("tinyint");

                    b.Property<byte>("equipa3")
                        .HasColumnType("tinyint");

                    b.Property<byte>("equipa4")
                        .HasColumnType("tinyint");

                    b.Property<string>("grupo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("grupos");
                });

            modelBuilder.Entity("SertaCup_site.Models.Marcador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("equipa")
                        .HasColumnType("int");

                    b.Property<int>("jogo_id")
                        .HasColumnType("int");

                    b.Property<int>("marcador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("marcadores_jogo");
                });

            modelBuilder.Entity("SertaCup_site.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Equipa_id")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("jogadores");
                });

            modelBuilder.Entity("SertaCup_site.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor_Principal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cor_Secundaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Completo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("equipas");
                });
#pragma warning restore 612, 618
        }
    }
}
